# Example YAML configuration
version: 1.0
settings:
  enabled: true
  description: "Add your configuration details here"
  instructions:
    - "Use descriptive variable names."
    - "Keep functions small and focused."
    - "Avoid deep nesting of loops and conditionals."
    - "Use comments to explain complex logic."
    - "Follow the project's coding style guidelines."
    - "Write unit tests for new features."
    - "Use version control for all changes."
    - "Document public APIs and libraries."
    - "Use meaningful commit messages."
    - "Keep dependencies up to date."
    - "Use consistent formatting and linting tools."
    - "Avoid hardcoding values; use constants or configuration files."
    - "Use error handling to manage exceptions."
    - "Optimize for readability over cleverness."
    - "Use version control branches for new features."
    - "Review code before merging to the main branch."
    - "Use pull requests for code reviews."
    - "Test code in different environments before deployment."
    - "Use logging to track application behavior."
    - "Keep security in mind; validate user inputs."
    - "Use environment variables for sensitive information."
    - "Follow the principle of least privilege for access control."
    - "Use design patterns where appropriate."
    - "Keep performance in mind; profile and optimize as needed."
    - "Use descriptive commit messages."
    - "Avoid premature optimization; focus on clarity first."
    - "Use version control tags for releases."
    - "Use semantic versioning for version control."
    - "Use code reviews to share knowledge and improve quality."
    - "Use feature flags for new features."
    - "Use CI/CD pipelines for automated testing and deployment."
    - "Use containerization for consistent development environments."
    - "Use code linters to enforce coding standards."
    - "Use static analysis tools to catch potential issues."
    - "Use dependency management tools to handle libraries."
    - "Use documentation generators to create API docs."
    - "Use code coverage tools to measure test effectiveness."
    - "Use performance monitoring tools to track application health."
    - "Use profiling tools to identify performance bottlenecks."
    - "Use caching to improve performance."
    - "Use database migrations for schema changes."
    - "Use ORM tools for database interactions."
    - "Use RESTful APIs for web services."
    - "Use GraphQL for flexible data queries."
    - "Use WebSockets for real-time communication."
    - "Use message queues for asynchronous processing."
    - "Use microservices architecture for scalability."
    - "Use serverless architecture for cost efficiency."
    - "Use cloud services for scalability and reliability."
    - "Use load balancers for traffic distribution."
    - "Use CDNs for static asset delivery."
    - "Use monitoring tools to track application performance."
    - "Use alerting tools to notify of issues."
